[options]
addons_path = /home/niini/odoo18/addons,/home/niini/odoo-fms/addons
admin_passwd = fms_dev_only
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
xmlrpc_port = 8069
logfile = /home/niini/odoo-fms/.logs/odoo.log
log_level = info
